### ISSUE TITLE
Error message in val.py

### ISSUE THREAD

**Issue by ZePinto99** [mikel-brostrom/Yolov5_StrongSORT_OSNet#548]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov5_StrongSORT_OSNet Component

Evaluation

### Bug

When trying to evaluate the model the fallowing error message appears.

> Tracker file not found: /content/Yolov5_StrongSORT_OSNet/val_utils/data/trackers/mot_challenge/MOT16-train/exp2/data/MOT16-02.txt
Traceback (most recent call last):
  File "val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/content/Yolov5_StrongSORT_OSNet/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 126, in __init__
    curr_file))
trackeval.utils.TrackEvalException: Tracker file not found: exp2/data/MOT16-02.txt

**Comment by mikel-brostrom** [comment]
This is not something that I would recommend to run in Colab as it is very computationally expensive . For this same reason I have never run the val script there. 

If you still want to do it, provide the whole val output for help, as there are many steps that need to execute correctly

**Comment by ZePinto99** [comment]
Hi, I tried to run the script on other hardware before trying Colab and got the same issue.

> Tracker file not found: /notebooks/disk2/jose/Yolov5_StrongSORT_OSNet/val_utils/data/trackers/mot_challenge/MOT16-train/exp8/data/MOT16-02.txt
Traceback (most recent call last):
  File "/notebooks/disk2/jose/Yolov5_StrongSORT_OSNet/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/notebooks/disk2/jose/Yolov5_StrongSORT_OSNet/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: exp8/data/MOT16-02.txt

**Comment by mikel-brostrom** [comment]
The complete output, please

**Comment by ZePinto99** [comment]
Sorry for the late reply. I'm actually trying to run this on hardware that I have access to, the Colab was only a test because my GPU was busy trainning a detection model.
I found out that the issue I was having was that my CUDA ao Pytorch versions were not compatible.

**Comment by itepifanio** [comment]
@mikel-brostrom I'm facing the same problem (`trackeval.utils.TrackEvalException: Tracker file not found: exp2/data/MOT16-02.txt`) when running locally using CPU with the latest code.

To make `val.py` work I had to add some subprocess to download the `crowdhuman_yolov5m.pt`

```
subprocess.run(['mkdir', '-p', 'yolov5/weights'])
subprocess.run([
    'wget', 
    '-nc', 
    'https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/releases/download/v.2.0/crowdhuman_yolov5m.pt', 
    '-O', 
    'yolov5/weights/crowdhuman_yolov5m.pt'
])
subprocess.run(['mkdir', '-p', 'weights'])
subprocess.run(['cp', 'yolov5/weights/crowdhuman_yolov5m.pt', './weights/crowdhuman_yolov5m.pt'])
```

Then I changed `device = i % (nr_gpus or 1)` to use `device = 'cpu'` and removed the `--eval` to avoid the GPU.

After tracking everything I'm facing `trackeval.utils.TrackEvalException: Tracker file not found: exp2/data/MOT16-02.txt`, for some reason some files *.txt aren't copied, while others are.

PS: I'll post the whole output when I finish the current execution

**Comment by mikel-brostrom** [comment]
> trackeval.utils.TrackEvalException: Tracker file not found: exp2/data/MOT16-02.txt

I had this problem yesterday. It should be solved. `git pull` and try again

> Then I changed `device = i % (nr_gpus or 1)` to use` device = 'cpu' `and removed the` --eval` to avoid the GPU.

Sure, I just don't see the point in running the evaluation on CPU as it would take hours to run I guess

**Comment by itepifanio** [comment]
> I had this problem yesterday. It should be solved. git pull and try again

@mikel-brostrom thanks, it worked :D 

> Sure, I just don't see the point in running the evaluation on CPU

I was facing an issue with the GPU, and while fixing I left the evaluation being executed on the CPU.

I still didn't fix it, but it's probably not related to your work. 

```
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 328, in <module>
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 328, in <module>
    main(opt)
    main(opt)
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 323, in main
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 323, in main
    run(**vars(opt))
  File "/home/dev/miniconda3/envs/cuda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    run(**vars(opt))
  File "/home/dev/miniconda3/envs/cuda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 145, in run
    return func(*args, **kwargs)
  File "/home/dev/Yolov5_StrongSORT_OSNet/track.py", line 145, in run
    t1 = time_sync()
    t1 = time_sync()
  File "/home/dev/Yolov5_StrongSORT_OSNet/yolov5/utils/torch_utils.py", line 146, in time_sync
  File "/home/dev/Yolov5_StrongSORT_OSNet/yolov5/utils/torch_utils.py", line 146, in time_sync
    torch.cuda.synchronize()
    torch.cuda.synchronize()
  File "/home/dev/miniconda3/envs/cuda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 496, in synchronize
  File "/home/dev/miniconda3/envs/cuda/lib/python3.9/site-packages/torch/cuda/__init__.py", line 496, in synchronize
    return torch._C._cuda_synchronize()
    return torch._C._cuda_synchronize()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be inco![](Screenshot from 2022-10-26 15-05-12.png)rrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
