### ISSUE TITLE
when starting object detection, crashes

### ISSUE THREAD

**Issue by spinxi** [mikel-brostrom/Yolov5_StrongSORT_OSNet#664]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

I cloned fresh copy. installed dependencies, run it and as soon as something gets detected, it crashes
It happens when --tracking-method is set to Strongsort

.
.
.
.
when saving --save-crop

```
    save_one_box(bbox.astype(np.int16), imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)
AttributeError: 'list' object has no attribute 'astype'
```

### Environment

CUDA 116 
I'm running it on GPU

### Minimal Reproducible Example

```
Successfully loaded pretrained weights from "C:\Users\NVR_SERVER_USA\Desktop\Project_File\OSNET\weights\osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
0: 384x640 1 tv, 537.7ms
Traceback (most recent call last):
  File "C:\Users\NVR_SERVER_USA\Desktop\Project_File\OSNET\track.py", line 342, in <module>
    main(opt)
  File "C:\Users\NVR_SERVER_USA\Desktop\Project_File\OSNET\track.py", line 337, in main
    run(**vars(opt))
  File "C:\Users\NVR_SERVER_USA\Desktop\Project_File\envv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\NVR_SERVER_USA\Desktop\Project_File\OSNET\track.py", line 211, in run
    outputs[i] = tracker_list[i].update(det.cpu(), im0)
  File "C:\Users\NVR_SERVER_USA\Desktop\Project_File\OSNET\trackers\strong_sort\strong_sort.py", line 79, in update
    outputs.append(np.array([x1, y1, x2, y2, track_id, class_id, conf, queue]))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (8,) + inhomogeneous part.
```

**Comment by jjaegii** [comment]
i have fixed that
[fbc2427d98a46b67a8363745cf5bd730c53e896c](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/pull/666)

**Comment by mikel-brostrom** [comment]
@jjaegii PR was merged yesterday :smile:. This is now fixed

**Comment by Swalii** [comment]
@mikel-brostrom I am still facing the same issue  with -`-save-crop` 

```
 File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 344, in <module>
    main(opt)
  File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 339, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/Documents/Workspace/Yolov5_StrongSORT_OSNet/track.py", line 246, in run
    save_one_box(bbox.astype(np.int16), imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)
AttributeError: 'list' object has no attribute 'astype'

```

I am on the master branch and git log shows latest changes 

```
commit cd17bbaf329f33e3947783b317a544bbf1740cd8 (HEAD -> master, origin/master, origin/HEAD)
Author: mikel.brostrom <>
Date:   Mon Jan 9 11:08:45 2023 +0000

    fix broken import
```
let me know if anything I have missed , thanks for the awesome work
